name: todo_list
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  signals: ^5.2.1
  signals_flutter: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
